## Production docker-compose.yml file

version: '3'

services:
  frontend:
    command: npm start
    # Alternatively build your own images as you go with "build:"
    image: sinyman/weatherapp_frontend:2
    ports:
      - '8000:8000'
    env_file:
      - .prod-variables.env
    depends_on:
      - backend

  backend:
    command: npm start
    # Alternatively build your own images as you go with "build:"
    image: sinyman/weatherapp_backend:2
    ports:
      - '9000:9000'
    env_file:
    - .backend.env